NH-19125-Fix-W3C-Trace-Context-Implementation
solarwindscloud/solarwinds-apm-node pull request #16
Opened 2022-08-16 21:50 UTC by ronilan

## Overview

The pair passed down from agent to bindings and then to oboe is named `traceparent` and `tracestate`, however, what oboe actually is expecting for “tracestate” is not the `tracestate` string received, but rather the value in the key value pair representing our org in the `tracestate` string.

Something like:
`77771111aaaa0011-01`

See: https://github.com/librato/solarwinds-apm-liboboe/blob/165c750abc29a883ec744c5fec1035cbe8522454/liboboe/oboe.h#L237

## Status

Current implementation naively takes the first value from a key value pair in the `tracestate` string and passes it down to oboe.

## Fix

- Our value is extracted from any string and passed down.
- Test cases added.

2022-08-17 16:09 UTC, cheempz requested changes
Thanks for catching this @ronilan (and @tammy-baylis-swi for asking in previous PR about the meaning of tracestate).  I left some comments.

2022-08-17 16:09 UTC, cheempz commented on docs/migrating.md
> +- Agent now support W3C Trace Context propagation. Due to the implementation chosen, some functions related to trace now expect a traceparent and tracestate duo rather than a single xtrace value. Not
It looks like the API methods that expect "tracestate" value are the `startOrContinueTrace` and `getTraceSettings` calls which should only pass our vendor specific tracestate value to bindings.  So let's emphasize that this value should be taken from the `sw` vendor entry in any incoming tracestate carrier.

2022-08-17 16:09 UTC, cheempz commented on test/w3c-trace-context.test.js
> +        tracestate: 'a1=continue_from_me,a2=i_was_before'
Should `tracestate` be empty for this case?

2022-08-17 16:09 UTC, cheempz commented on test/probes/http-common.js
> +          expect(msg).property('sw.tracestate_parent_id')
On the two assertions above:

The `Edge` should link back to the span ID from the `traceparent` header, which is the same issue we discussed in https://swicloud.atlassian.net/browse/NH-14580 that needs to be addressed, can be in a separate PR if needed.

For `sw.tracestate_parent_id`, we should also assert that it captures our `sw` vendor key's span ID value from the incoming `tracestate` header.

2022-08-17 17:02 UTC, tammy-baylis-swi reviewed
Thanks Ron! Looks good and more like w3c acceptance criteria!

I agree with Lin's comments. I'll wait for those to be addressed before another pass.

2022-08-19 16:00 UTC, cheempz approved these changes
Approved to unblock this PR, noting that https://swicloud.atlassian.net/browse/NH-14580 remains unaddressed.

2022-08-19 16:03 UTC, merged